Lyncas.System.Portal/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Lyncas.System.Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Lyncas.System.Portal/Controllers/PesquisaController.cs
using Lyncas.Intra;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Lyncas.System.Portal.Controllers
{
    public class PesquisaController : Controller
    {
        [HttpPost]
        public ActionResult Livro(string Livro, string Pagina)
        {
            try
            {
                if (String.IsNullOrEmpty(Pagina))
                {
                    Pagina = "0";
                }
                var request = new ApiRequest().Post(Livro, Pagina);

                var lstObject = new List<string>();
                lstObject.Add(JsonConvert.SerializeObject(request));

                return Json(lstObject.ToArray(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception Error)
            {
                return Json(Error.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Lyncas.System.Portal/Controllers/SistemaController.cs
using System.Web.Mvc;

namespace Lyncas.System.Portal.Controllers
{
    public class SistemaController : Controller
    {
        public ActionResult Pesquisa()
        {
            return View();
        }

        public ActionResult Favoritos()
        {
            return View();
        }
    }
}

Lyncas.System.Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página inicial";
}

<div class="row">
    <h1>Bem vindo(a),</h1>
    <p>Abaixo teremos os detalhes para elaboração do projeto.</p>
    <hr />
    <p>
        Desenvolvido por: Tiago Pereira Cardoso<br />
        Email: tiagocardosso@gmail.com<br />
        Celular: (27) 99616 - 6969
    </p>
    <hr />
</div>

<div class="row page">
    <div class="file-content md">
        <h1 data-sourcepos="1:1-1:24" dir="auto">
            <a id="user-content-teste-para-net-c-dev" class="anchor" href="#teste-para-net-c-dev" aria-hidden="true"></a>Teste para .Net C# Dev
        </h1>
        <p data-sourcepos="3:1-3:265" dir="auto"><a href="https://www.lyncas.net" rel="nofollow noreferrer noopener" target="_blank"><img src="https://user-content.gitlab-static.net/434b540e2aa252c473b7aaf5109ed908d51b707b/68747470733a2f2f696d672d6465762e666565646261636b2e686f7573652f54436f357a3944725379583045516f616b5638734a6b78316d53673d2f6669742d696e2f333030783330302f736d6172742f68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f666565646261636b686f7573652d6d656469612d646576656c6f706d656e742f6d6f64756c6573253246636f7265253246636f6d70616e792532463563396531623031633566336430303033633566613533622532466c6f676f253246356339656334663836396431636230303363623739393664" alt="Lyncas Logo" data-canonical-src="https://img-dev.feedback.house/TCo5z9DrSyX0EQoakV8sJkx1mSg=/fit-in/300x300/smart/https://s3.amazonaws.com/feedbackhouse-media-development/modules%2Fcore%2Fcompany%2F5c9e1b01c5f3d0003c5fa53b%2Flogo%2F5c9ec4f869d1cb003cb7996d" class="js-lazy-loaded qa-js-lazy-loaded" loading="lazy"></a></p>
        <h3 data-sourcepos="4:1-4:14" dir="auto">
            <a id="user-content-requisitos" class="anchor" href="#requisitos" aria-hidden="true"></a>Requisitos
        </h3>
        <ul data-sourcepos="6:1-7:0" dir="auto">
            <li data-sourcepos="6:1-7:0">Google books (<a href="https://developers.google.com/books/" rel="nofollow noreferrer noopener" target="_blank">https://developers.google.com/books/</a>)</li>
        </ul>
        <h3 data-sourcepos="8:1-8:15" dir="auto">
            <a id="user-content-diferencial" class="anchor" href="#diferencial" aria-hidden="true"></a>Diferencial
        </h3>
        <ul data-sourcepos="10:1-12:0" dir="auto">
            <li data-sourcepos="10:1-10:19">Testes unitários</li>
            <li data-sourcepos="11:1-12:0">Backend e frontend em microserviços distintos</li>
        </ul>
        <h2 data-sourcepos="13:1-13:19" dir="auto">
            <a id="user-content-como-participar" class="anchor" href="#como-participar" aria-hidden="true"></a>Como participar?
        </h2>
        <ol data-sourcepos="15:1-18:0" dir="auto">
            <li data-sourcepos="15:1-15:37">Faça um clone deste repositório.</li>
            <li data-sourcepos="16:1-16:151">Quando estiver finalizado a prova, compartilhe seu código no seu Git de preferência e nos envie para o e-mail que consta ao final desse documento.</li>
            <li data-sourcepos="17:1-18:0">Faremos nossa análise e te daremos um retorno.</li>
        </ol>
        <h2 data-sourcepos="19:1-19:20" dir="auto">
            <a id="user-content-detalhes-da-prova" class="anchor" href="#detalhes-da-prova" aria-hidden="true"></a>Detalhes da prova
        </h2>
        <h3 data-sourcepos="21:1-21:25" dir="auto">
            <a id="user-content-critérios-analisados" class="anchor" href="#crit%C3%A9rios-analisados" aria-hidden="true"></a>Critérios analisados
        </h3>
        <ul data-sourcepos="23:1-26:0" dir="auto">
            <li data-sourcepos="23:1-23:34">Arquitetura do projeto (camadas)</li>
            <li data-sourcepos="24:1-24:38">Aplicação de orientação a objeto</li>
            <li data-sourcepos="25:1-26:0">Funcionalidades e funcionamento</li>
        </ul>
        <h3 data-sourcepos="27:1-27:32" dir="auto">
            <a id="user-content-o-que-você-deve-desenvolver" class="anchor" href="#o-que-voc%C3%AA-deve-desenvolver" aria-hidden="true"></a>O que você deve desenvolver
        </h3>
        <ul data-sourcepos="29:1-34:0" dir="auto">
            <li data-sourcepos="29:1-29:82">A prova consiste em criar uma interface Web para interação com o Google books.</li>
            <li data-sourcepos="30:1-30:127">Seu projeto deve também conter um arquivo README com a explicação das tecnologias utilizadas e as instruções para rodar.</li>
            <li data-sourcepos="31:1-31:92">Descrever suas dificuldades e facilidades, bem como o número de horas de desenvolvimento.</li>
            <li data-sourcepos="32:1-32:136">A comunicação com o Google Books API deve ser feita utilizando um HttpClient padrão, feito na mão e sem o uso de qualquer library.</li>
            <li data-sourcepos="33:1-34:0">O Google Books API é aberto e não requer nenhuam autenticação.</li>
        </ul>
        <h3 data-sourcepos="35:1-35:19" dir="auto">
            <a id="user-content-funcionalidades" class="anchor" href="#funcionalidades" aria-hidden="true"></a>Funcionalidades
        </h3>
        <p data-sourcepos="37:1-37:47" dir="auto">A App deve conter as seguintes funcionalidades:</p>
        <p data-sourcepos="39:1-39:38" dir="auto">São 2 menus: Pesquisa, Meus favoritos</p>
        <ol data-sourcepos="41:1-45:0" dir="auto">
            <li data-sourcepos="41:1-41:88">Pesquisar livros no Google books e exibir em tela (com a foto e descrição resumida)</li>
            <li data-sourcepos="42:1-42:80">Salvar livros em uma lista de "meus favoritos" (localmente na base escolhida)</li>
            <li data-sourcepos="43:1-43:36">Listar e excluir livros favoritos</li>
            <li data-sourcepos="44:1-45:0">Exibir alerta de confirmaçao de exclusão</li>
        </ol>
        <h3 data-sourcepos="46:1-46:30" dir="auto">
            <a id="user-content-especificações-técnicas" class="anchor" href="#especifica%C3%A7%C3%B5es-t%C3%A9cnicas" aria-hidden="true"></a>Especificações técnicas
        </h3>
        <ul data-sourcepos="48:1-50:0" dir="auto">
            <li data-sourcepos="48:1-48:98">O App deve se comunicar com o Google Books API pelo backend .Net e não fazer uso de nenhuma lib</li>
            <li data-sourcepos="49:1-50:0">Você pode optar pelo padrão MVC ou Front-end separado.</li>
        </ul>
        <h2 data-sourcepos="51:1-51:28" dir="auto">
            <a id="user-content-dúvidas-envio-da-prova" class="anchor" href="#d%C3%BAvidas-envio-da-prova" aria-hidden="true"></a>Dúvidas? Envio da prova?
        </h2>
        <p data-sourcepos="52:1-52:19" dir="auto"><code>testes@lyncas.net</code></p>
        <h3 data-sourcepos="54:1-54:54" dir="auto">
            <a id="user-content-desde-já-obrigado-pelo-seu-interesse-e-boa-prova" class="anchor" href="#desde-j%C3%A1-obrigado-pelo-seu-interesse-e-boa-prova" aria-hidden="true"></a>Desde já obrigado pelo seu interesse e boa prova!
        </h3>
    </div>
</div>

Lyncas.System.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Google Books</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div id="loadingPage">
        <center>
            <div class="itemloading circleloading">
                <div class="barloading bar1loading"></div>
                <div class="barloading bar2loading"></div>
                <div class="barloading bar3loading"></div>
                <div class="barloading bar4loading"></div>
                <div class="barloading bar5loading"></div>
                <div class="barloading bar6loading"></div>
                <div class="barloading bar7loading"></div>
                <div class="barloading bar8loading"></div>
                <div class="barloading bar9loading"></div>
                <div class="barloading bar10loading"></div>
                <div class="barloading bar11loading"></div>
                <div class="barloading bar12loading"></div>
            </div>
            <br />
            Aguarde ...
        </center>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Google Books", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pesquisa", "Pesquisa", "Sistema")</li>
                    <li>@Html.ActionLink("Meus favoritos", "Favoritos", "Sistema")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Google Books</p>
        </footer>
    </div>

    <div class="modal" tabindex="-1" role="dialog" style="background: #000000b0;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body"></div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -35px; margin-right: 17px;">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script>
    <script src="~/Scripts/jquery-ajax.js"></script>
    <script src="~/Scripts/Page/Todos.js"></script>
</body>
</html>

Lyncas.System.Portal/Views/Sistema/Favoritos.cshtml
@{
    ViewBag.Title = "Favoritos";
}
<script src="~/Scripts/Page/Favoritos.js"></script>

<h2>Favoritos</h2>
<hr />
<div class="page">
    <div id="resultado-final"></div>
</div>

Lyncas.System.Portal/Views/Sistema/Pesquisa.cshtml
@{
    ViewBag.Title = "Pesquisa";
}
<script src="~/Scripts/Page/Pesquisa.js"></script>

<h2>Pesquisa</h2>
<hr />
<div class="div-flex">
    <div class="max"><input class="form-control max-input" type="text" id="nomeLivro" placeholder="Digite o nome do livro" /></div>
    <div><a class="btn btn-primary" onclick="PesquisarLivro()"><i class="fa fa-search" aria-hidden="true"></i> Pesquisar</a></div>
</div>
<div id="pagina-resultado" style="display: none;">
    <hr />

    <div class="page">
        <div style="display: none">
            <select class="form-control" id="pagina"></select>
        </div>

        <div id="resultado-final"></div>
    </div>
</div>